Implement backend jwt
Mahatmasamatman/ig pull request #2
Opened 2021-12-10 22:01 UTC by Mahatmasamatman

Change to /users route:
- when the user successfully creates his account, the response now contains a JWT so he can automatically access protected routes.

Change to /auth route:
- there is now a POST method, that is used to authenticate the users provided email and password. On successful validation, the route returns a JWT.

There is now a middleware function in middleware/auth.js that will be used in all of the protected routes, to check the validity of the token and provide information about the user doing the request.

2021-12-10 22:19 UTC, frle10 commented on api/auth.js
> +//@desc   Test route, recieves a token and returns info about users profile
receives* typo

2021-12-10 22:24 UTC, frle10 commented on middleware/auth.js
> +      if (error) {
The convention is to always put the main action in the if part, and the error handling in else. This is because we want the code reader to focus on the main idea behind the code first, and not error handling. So, in this case you would reverse the if and else block and it would look like:

`if (!error) {
   req.user = decoded.user;
   next();
} else {
   return res.status(401).json({ msg: 'Token is not valid' });
}`

2021-12-10 22:25 UTC, frle10 requested changes
Looks pretty good, resolve the discussions and I will approve. :)

2022-03-12 16:19 UTC, Mahatmasamatman reviewed
Fixed issues

2022-03-12 16:20 UTC, merged